version: '3'
services:
  db:
    image: 'postgres:11'
    container_name: 'my_postgres'
    ports:
      - '5432:5432'
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    env_file:
      - .env
  pg_admin:
    image: 'dpage/pgadmin4'
    container_name: 'my_pg_admin'
    ports:
      - '5555:80'
    env_file:
      - .env
volumes:
  my_dbdata: {}
